name: loyalbazaar
description: A professional mobile application for small businesses in Tier-2 and Tier-3 towns in India to manage customer loyalty programs easily and affordably.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  firebase_core: ^3.13.1
  firebase_messaging: ^15.1.6
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  cloud_functions: ^5.5.0
  google_maps_flutter: ^2.5.3
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
